name: petcare
description: PetCare - Aplikasi perawatan hewan peliharaan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO_PawPet.PNG

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/LOGO_PawPet.PNG"
  background_color: "#FFF8F3"
  adaptive_icon_background: "#FFF8F3"
  adaptive_icon_foreground: "assets/images/LOGO_PawPet.PNG"