name: petcare
description: PetCare - Aplikasi perawatan hewan peliharaan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  flutter_native_splash: ^2.4.0
  http: ^1.6.0
  flutter_secure_storage: ^10.1.0
  intl: ^0.20.2
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/PawPetlogo.svg
    - assets/images/PawPetNew.png
    - assets/images/paw3.png
    - assets/images/dokterHewan.jpg
    - assets/images/grooming.jpg
    - assets/images/boarding.jpg
    - assets/images/dokter1.jpg
    - assets/images/iklan1.jpg
    - assets/images/iklan2.jpg
    - assets/images/iklan3.jpg
    - assets/images/product1.jpg
    - assets/images/product2.jpg
    - assets/images/product3.jpg
    - assets/images/product4.jpg
    - assets/images/product5.jpg
    - assets/images/product6.jpg
    - assets/images/product7.jpg
    - assets/images/product8.jpg
    - assets/images/product9.jpg 
    - assets/images/product10.jpg
    - assets/images/buddy.jpg
    - assets/images/charlie.jpg
    - assets/images/mittens.jpg
    - assets/images/grooming.png
    - assets/images/pet-boarding.png
    - assets/images/pet-dokter.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/PawPetNew.png"
  background_color: "#FFF8F3"
  adaptive_icon_background: "#FFF8F3"
  adaptive_icon_foreground: "assets/images/PawPetNew.png"

flutter_native_splash:
  color: "#FFF8F3"
  image: assets/images/PawPetNew.png
  color_dark: "#FFF8F3"
  android: true
  ios: true
  android_12:
    color: "#FFF8F3"
    image: assets/images/PawPetNew.png